packages:
    - ./packages/*
    - ./tests/*
    - ./plugins/*
    - ./templates/*

catalogs:
    dep:
        es-toolkit: ^1.40.0
        lightningcss: ^1.30.0
        oxc-parser: ~0.111.0
        oxc-minify: ~0.111.0
        rolldown: 1.0.0-rc.2
        ts-vista: ~0.2.3
        vitest: ^4.0.0
        vite-tsconfig-paths: ^6.0.0
    dev:
        # webpack
        webpack: 5.76.0
        html-webpack-plugin: 5.6.1
        # rollup
        rollup: 4.40.0
        # vite
        vite: 7.0.0
    peer:
        # webpack
        webpack: ^5.76.0
        html-webpack-plugin: ^5.6.1
        # rollup
        rollup: ^4.40.0
        # vite
        vite: ^7.0.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    - "ts-vista"
