packages:
    - ./packages/*
    - ./tests/*
    - ./plugins/*
    - ./templates/*
    - ./examples/*

catalogs:
    dep:
        es-toolkit: ^1.40.0
        fdir: ^6.5.0
        ts-vista: ~0.2.3
        # webpack
        css-loader: ^7.1.3
        # postcss
        "@types/postcss-preset-env": ^8.0.0
        postcss-flexbugs-fixes: ^5.0.0
        postcss-load-config: ^6.0.0
        postcss-preset-env: ^11.0.0
        # oxc
        oxc-parser: ~0.112.0
        oxc-minify: ~0.112.0
        rolldown: 1.0.0-rc.3
        # vite
        vitest: ^4.0.0
        vite-tsconfig-paths: ^6.0.0
        # react
        "@types/react": ^19.0.0
        "@types/react-dom": ^19.0.0
        react: ^19.0.0
        react-dom: ^19.0.0
    dev:
        # webpack
        webpack: 5.76.0
        # rollup
        rollup: 4.40.0
        # rolldown
        rolldown: 1.0.0-rc.3
        # vite
        vite: 7.0.0
        # postcss
        postcss: 8.5.0
    peer:
        # webpack
        webpack: ^5.76.0
        # rollup
        rollup: ^4.40.0
        # rolldown
        rolldown: 1.0.0-rc.3
        # vite
        vite: ^7.0.0
        # postcss
        postcss: ^8.5.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    - "ts-vista"
